
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 967745
	#The name of the modpack
	modpackName = "All the Mods 9 - To the Sky - atm9sky"
	#The version of the modpack
	modpackVersion = "1.1.8"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

